# symbol_buckets.py — auto-generated from TOP 500 list
# Buckets are used by the data agent to schedule staggered refreshes.
BUCKETS = {
  'CORE_1': [
    {'key': 'club-token', 'name': 'Club Token', 'symbol': 'KOGE'},
    {'key': 'dogecoin', 'name': 'Dogecoin', 'symbol': 'DOGE'},
    {'key': 'avalanche', 'name': 'Avalanche', 'symbol': 'AVAX'},
    {'key': 'cronos', 'name': 'Cronos', 'symbol': 'CRO'},
    {'key': 'bitget-token', 'name': 'Bitget Token', 'symbol': 'BGB'},
    {'key': 'aster', 'name': 'Aster', 'symbol': 'ASTER'},
    {'key': 'arbitrum', 'name': 'Arbitrum', 'symbol': 'ARB'},
    {'key': 'vechain', 'name': 'VeChain', 'symbol': 'VET'},
    {'key': 'official-trump', 'name': 'OFFICIAL TRUMP', 'symbol': 'TRUMP'},
    {'key': 'pancakeswap', 'name': 'PancakeSwap', 'symbol': 'CAKE'},
    {'key': 'stacks', 'name': 'Stacks', 'symbol': 'STX'},
    {'key': 'floki', 'name': 'FLOKI', 'symbol': 'FLOKI'},
    {'key': 'pendle', 'name': 'Pendle', 'symbol': 'PENDLE'},
    {'key': 'virtuals-protocol', 'name': 'Virtuals Protocol', 'symbol': 'VIRTUAL'},
    {'key': 'decentraland', 'name': 'Decentraland', 'symbol': 'MANA'},
    {'key': 'deepbook-protocol', 'name': 'DeepBook Protocol', 'symbol': 'DEEP'},
    {'key': 'usdd', 'name': 'USDD', 'symbol': 'USDD'},
    {'key': 'neo', 'name': 'Neo', 'symbol': 'NEO'},
    {'key': 'synthetix', 'name': 'Synthetix', 'symbol': 'SNX'},
    {'key': 'axie-infinity', 'name': 'Axie Infinity', 'symbol': 'AXS'},
    {'key': 'berachain', 'name': 'Berachain', 'symbol': 'BERA'},
    {'key': 'decred', 'name': 'Decred', 'symbol': 'DCR'},
    {'key': 'wemix', 'name': 'WEMIX', 'symbol': 'WEMIX'},
    {'key': 'safepal', 'name': 'SafePal', 'symbol': 'SFP'},
    {'key': 'safe', 'name': 'Safe', 'symbol': 'SAFE'},
    {'key': 'dog-bitcoin', 'name': 'Dog (Bitcoin)', 'symbol': 'DOG'},
    {'key': 'apx', 'name': 'APX', 'symbol': 'APX'},
    {'key': 'vision', 'name': 'Vision', 'symbol': 'VSN'},
    {'key': 'ribbita-by-virtuals', 'name': 'Ribbita by Virtuals', 'symbol': 'TIBBIR'},
    {'key': 'avantis', 'name': 'Avantis', 'symbol': 'AVNT'},
    {'key': 'legacy-token', 'name': 'Legacy Token', 'symbol': 'LGCT'},
    {'key': 'go-ining', 'name': 'GoМining', 'symbol': 'GOMINING'},
    {'key': 'oasis', 'name': 'Oasis', 'symbol': 'ROSE'},
    {'key': 'whiterock', 'name': 'WhiteRock', 'symbol': 'WHITE'},
    {'key': 'ultima', 'name': 'Ultima', 'symbol': 'ULTIMA'},
    {'key': 'official-melania-meme', 'name': 'Official Melania Meme', 'symbol': 'MELANIA'},
    {'key': 'vethor-token', 'name': 'VeThor Token', 'symbol': 'VTHO'},
    {'key': 'quantum-resistant-ledger', 'name': 'Quantum Resistant Ledger', 'symbol': 'QRL'},
    {'key': 'memecoin', 'name': 'Memecoin', 'symbol': 'MEME'},
    {'key': 'babylon', 'name': 'Babylon', 'symbol': 'BABY'},
    {'key': 'icon', 'name': 'ICON', 'symbol': 'ICX'},
    {'key': 'coti', 'name': 'COTI', 'symbol': 'COTI'},
    {'key': 'loopring', 'name': 'Loopring', 'symbol': 'LRC'},
    {'key': 'osmosis', 'name': 'Osmosis', 'symbol': 'OSMO'},
    {'key': 'io-net', 'name': 'io.net', 'symbol': 'IO'},
    {'key': 'request', 'name': 'Request', 'symbol': 'REQ'},
    {'key': 'yield-guild-games', 'name': 'Yield Guild Games', 'symbol': 'YGG'},
    {'key': 'magic-eden', 'name': 'Magic Eden', 'symbol': 'ME'},
    {'key': 'funtoken', 'name': 'FUNToken', 'symbol': 'FUN'},
    {'key': 'sologenic', 'name': 'Sologenic', 'symbol': 'SOLO'},
    {'key': 'mira', 'name': 'Mira', 'symbol': 'MIRA'},
    {'key': 'nomina', 'name': 'Nomina', 'symbol': 'NOM'},
    {'key': 'swftcoin', 'name': 'SwftCoin', 'symbol': 'SWFTC'},
    {'key': 'bim', 'name': 'BIM', 'symbol': 'BIM'},
    {'key': 'cyber', 'name': 'Cyber', 'symbol': 'CYBER'},
    {'key': 'huma-finance', 'name': 'Huma Finance', 'symbol': 'HUMA'},
    {'key': 'quantixai', 'name': 'QuantixAI', 'symbol': 'QAI'},
    {'key': 'mvl', 'name': 'MVL', 'symbol': 'MVL'},
    {'key': 'carv', 'name': 'CARV', 'symbol': 'CARV'},
    {'key': 'api3', 'name': 'API3', 'symbol': 'API3'},
    {'key': 'spacen', 'name': 'SpaceN', 'symbol': 'SN'},
    {'key': 'pirate-chain', 'name': 'Pirate Chain', 'symbol': 'ARRR'},
    {'key': 'orbs', 'name': 'Orbs', 'symbol': 'ORBS'},
  ],
  'CORE_2': [
    {'key': 'bitcoin', 'name': 'Bitcoin', 'symbol': 'BTC'},
    {'key': 'tron', 'name': 'TRON', 'symbol': 'TRX'},
    {'key': 'bitcoin-cash', 'name': 'Bitcoin Cash', 'symbol': 'BCH'},
    {'key': 'polkadot', 'name': 'Polkadot', 'symbol': 'DOT'},
    {'key': 'ethena', 'name': 'Ethena', 'symbol': 'ENA'},
    {'key': 'story', 'name': 'Story', 'symbol': 'IP'},
    {'key': 'memecore', 'name': 'MemeCore', 'symbol': 'M'},
    {'key': 'pi', 'name': 'Pi', 'symbol': 'PI'},
    {'key': 'jupiter', 'name': 'Jupiter', 'symbol': 'JUP'},
    {'key': 'optimism', 'name': 'Optimism', 'symbol': 'OP'},
    {'key': 'lido-dao', 'name': 'Lido DAO', 'symbol': 'LDO'},
    {'key': 'kaia', 'name': 'Kaia', 'symbol': 'KAIA'},
    {'key': 'iota', 'name': 'IOTA', 'symbol': 'IOTA'},
    {'key': 'eigenlayer', 'name': 'EigenLayer', 'symbol': 'EIGEN'},
    {'key': 'vaulta', 'name': 'Vaulta', 'symbol': 'A'},
    {'key': 'walrus', 'name': 'Walrus', 'symbol': 'WAL'},
    {'key': 'maple-finance', 'name': 'Maple Finance', 'symbol': 'SYRUP'},
    {'key': 'beam', 'name': 'Beam', 'symbol': 'BEAM'},
    {'key': 'linea', 'name': 'Linea', 'symbol': 'LINEA'},
    {'key': 'cheems-cheems-pet', 'name': 'Cheems (cheems.pet)', 'symbol': 'CHEEMS'},
    {'key': 'falcon-finance', 'name': 'Falcon Finance', 'symbol': 'FF'},
    {'key': 'plume', 'name': 'Plume', 'symbol': 'PLUME'},
    {'key': 'ftx-token', 'name': 'FTX Token', 'symbol': 'FTT'},
    {'key': 'amp', 'name': 'Amp', 'symbol': 'AMP'},
    {'key': 'cat-in-a-dogs-world', 'name': 'cat in a dogs world', 'symbol': 'MEW'},
    {'key': 'jupiter-perps-lp', 'name': 'Jupiter Perps LP', 'symbol': 'JLP'},
    {'key': 'ondo-us-dollar-yield', 'name': 'Ondo US Dollar Yield', 'symbol': 'USDY'},
    {'key': 'ai-companions', 'name': 'AI Companions', 'symbol': 'AIC'},
    {'key': '', 'name': '币安人生', 'symbol': '币安人生'},
    {'key': 'subsquid', 'name': 'Subsquid', 'symbol': 'SQD'},
    {'key': 'peanut-the-squirrel', 'name': 'Peanut the Squirrel', 'symbol': 'PNUT'},
    {'key': 'bio-protocol', 'name': 'Bio Protocol', 'symbol': 'BIO'},
    {'key': 'vvs-finance', 'name': 'VVS Finance', 'symbol': 'VVS'},
    {'key': 'sahara-ai', 'name': 'Sahara AI', 'symbol': 'SAHARA'},
    {'key': 'xpr-network', 'name': 'XPR Network', 'symbol': 'XPR'},
    {'key': 'anoma', 'name': 'Anoma', 'symbol': 'XAN'},
    {'key': 'gems', 'name': 'Gems', 'symbol': 'GEMS'},
    {'key': 'aelf', 'name': 'aelf', 'symbol': 'ELF'},
    {'key': 'non-playable-coin', 'name': 'Non-Playable Coin', 'symbol': 'NPC'},
    {'key': 'troll-sol', 'name': 'TROLL (SOL)', 'symbol': 'TROLL'},
    {'key': 'numeraire', 'name': 'Numeraire', 'symbol': 'NMR'},
    {'key': 'somnia', 'name': 'Somnia', 'symbol': 'SOMI'},
    {'key': 'arkham', 'name': 'Arkham', 'symbol': 'ARKM'},
    {'key': 'ontology', 'name': 'Ontology', 'symbol': 'ONT'},
    {'key': 'band', 'name': 'Band', 'symbol': 'BAND'},
    {'key': 'undeads-games', 'name': 'Undeads Games', 'symbol': 'UDS'},
    {'key': 'paycoin', 'name': 'Paycoin', 'symbol': 'PCI'},
    {'key': 'ai16z', 'name': 'ai16z', 'symbol': 'AI16Z'},
    {'key': 'doodles', 'name': 'Doodles', 'symbol': 'DOOD'},
    {'key': 'tornado-cash', 'name': 'Tornado Cash', 'symbol': 'TORN'},
    {'key': 'tellor', 'name': 'Tellor', 'symbol': 'TRB'},
    {'key': 'giggle-fund', 'name': 'Giggle Fund', 'symbol': 'GIGGLE'},
    {'key': 'ark', 'name': 'Ark', 'symbol': 'ARK'},
    {'key': 'manta-network', 'name': 'Manta Network', 'symbol': 'MANTA'},
    {'key': 'pundi-x-new', 'name': 'Pundi X (New)', 'symbol': 'PUNDIX'},
    {'key': 'sats-ordinals', 'name': 'SATS (Ordinals)', 'symbol': 'SATS'},
    {'key': 'aura', 'name': 'Aura', 'symbol': 'AURA'},
    {'key': 'siren', 'name': 'siren', 'symbol': 'SIREN'},
    {'key': 'cross', 'name': 'CROSS', 'symbol': 'CROSS'},
    {'key': 'comedian', 'name': 'Comedian', 'symbol': 'BAN'},
    {'key': 'eur-coinvertible', 'name': 'EUR CoinVertible', 'symbol': 'EURCV'},
    {'key': 'debridge', 'name': 'deBridge', 'symbol': 'DBR'},
    {'key': 'ontology-gas', 'name': 'Ontology Gas', 'symbol': 'ONG'},
  ],
  'CORE_3': [
    {'key': 'ethereum', 'name': 'Ethereum', 'symbol': 'ETH'},
    {'key': 'cardano', 'name': 'Cardano', 'symbol': 'ADA'},
    {'key': 'litecoin', 'name': 'Litecoin', 'symbol': 'LTC'},
    {'key': 'monero', 'name': 'Monero', 'symbol': 'XMR'},
    {'key': 'pepe', 'name': 'Pepe', 'symbol': 'PEPE'},
    {'key': 'ondo', 'name': 'Ondo', 'symbol': 'ONDO'},
    {'key': 'kucoin-token', 'name': 'KuCoin Token', 'symbol': 'KCS'},
    {'key': 'sei', 'name': 'Sei', 'symbol': 'SEI'},
    {'key': 'plasma', 'name': 'Plasma', 'symbol': 'XPL'},
    {'key': 'quant', 'name': 'Quant', 'symbol': 'QNT'},
    {'key': 'curve-dao-token', 'name': 'Curve DAO Token', 'symbol': 'CRV'},
    {'key': 'the-graph', 'name': 'The Graph', 'symbol': 'GRT'},
    {'key': 'conflux', 'name': 'Conflux', 'symbol': 'CFX'},
    {'key': 'the-sandbox', 'name': 'The Sandbox', 'symbol': 'SAND'},
    {'key': 'jasmycoin', 'name': 'JasmyCoin', 'symbol': 'JASMY'},
    {'key': '0g', 'name': '0G', 'symbol': '0G'},
    {'key': 'four', 'name': 'Four', 'symbol': 'FORM'},
    {'key': 'brett-based', 'name': 'Brett (Based)', 'symbol': 'BRETT'},
    {'key': 'gnosis', 'name': 'Gnosis', 'symbol': 'GNO'},
    {'key': 'kava', 'name': 'Kava', 'symbol': 'KAVA'},
    {'key': 'merlin-chain', 'name': 'Merlin Chain', 'symbol': 'MERL'},
    {'key': 'axelar', 'name': 'Axelar', 'symbol': 'AXL'},
    {'key': 'livepeer', 'name': 'Livepeer', 'symbol': 'LPT'},
    {'key': 'qtum', 'name': 'Qtum', 'symbol': 'QTUM'},
    {'key': 'iotex', 'name': 'IoTeX', 'symbol': 'IOTX'},
    {'key': 'falcon-usd', 'name': 'Falcon USD', 'symbol': 'USDF'},
    {'key': 'usual-usd', 'name': 'Usual USD', 'symbol': 'USD0'},
    {'key': 'telcoin', 'name': 'Telcoin', 'symbol': 'TEL'},
    {'key': 'apex-protocol', 'name': 'ApeX Protocol', 'symbol': 'APEX'},
    {'key': 'astar', 'name': 'Astar', 'symbol': 'ASTR'},
    {'key': 'upcx', 'name': 'UPCX', 'symbol': 'UPC'},
    {'key': 'standx-dusd', 'name': 'StandX DUSD', 'symbol': 'DUSD'},
    {'key': 'rekt-rektcoin-com', 'name': 'Rekt (rektcoin.com)', 'symbol': 'REKT'},
    {'key': 'mantra', 'name': 'MANTRA', 'symbol': 'OM'},
    {'key': 'metaplex', 'name': 'Metaplex', 'symbol': 'MPLX'},
    {'key': 'zigchain', 'name': 'ZIGChain', 'symbol': 'ZIG'},
    {'key': 'stasis-euro', 'name': 'STASIS EURO', 'symbol': 'EURS'},
    {'key': 'digibyte', 'name': 'DigiByte', 'symbol': 'DGB'},
    {'key': 'world-mobile-token', 'name': 'World Mobile Token', 'symbol': 'WMTX'},
    {'key': 'altlayer', 'name': 'Altlayer', 'symbol': 'ALT'},
    {'key': 'verge', 'name': 'Verge', 'symbol': 'XVG'},
    {'key': 'openledger', 'name': 'OpenLedger', 'symbol': 'OPEN'},
    {'key': 'noble-dollar', 'name': 'Noble Dollar', 'symbol': 'USDN'},
    {'key': 'venus', 'name': 'Venus', 'symbol': 'XVS'},
    {'key': 'solayer', 'name': 'Solayer', 'symbol': 'LAYER'},
    {'key': 'status', 'name': 'Status', 'symbol': 'SNT'},
    {'key': 'gigachad', 'name': 'Gigachad', 'symbol': 'GIGA'},
    {'key': 'big-time', 'name': 'Big Time', 'symbol': 'BIGTIME'},
    {'key': 'illuvium', 'name': 'Illuvium', 'symbol': 'ILV'},
    {'key': 'orbler', 'name': 'Orbler', 'symbol': 'ORBR'},
    {'key': 'aevo', 'name': 'Aevo', 'symbol': 'AEVO'},
    {'key': 'bitdca', 'name': 'BitDCA', 'symbol': 'BDCA'},
    {'key': 'freysa', 'name': 'Freysa', 'symbol': 'FAI'},
    {'key': 'ardor', 'name': 'Ardor', 'symbol': 'ARDR'},
    {'key': 'constellation', 'name': 'Constellation', 'symbol': 'DAG'},
    {'key': 'frax-usd', 'name': 'Frax USD', 'symbol': 'FRXUSD'},
    {'key': 'caldera', 'name': 'Caldera', 'symbol': 'ERA'},
    {'key': 'lagrange', 'name': 'Lagrange', 'symbol': 'LA'},
    {'key': 'hivemapper', 'name': 'Hivemapper', 'symbol': 'HONEY'},
    {'key': 'liquity', 'name': 'Liquity', 'symbol': 'LQTY'},
    {'key': 'tokenlon-network-token', 'name': 'Tokenlon Network Token', 'symbol': 'LON'},
    {'key': 'marlin', 'name': 'Marlin', 'symbol': 'POND'},
    {'key': 'cartesi', 'name': 'Cartesi', 'symbol': 'CTSI'},
  ],
  'CORE_4': [
    {'key': 'tether', 'name': 'Tether', 'symbol': 'USDT'},
    {'key': 'chainlink', 'name': 'Chainlink', 'symbol': 'LINK'},
    {'key': 'hedera', 'name': 'Hedera', 'symbol': 'HBAR'},
    {'key': 'dai', 'name': 'Dai', 'symbol': 'DAI'},
    {'key': 'near-protocol', 'name': 'NEAR Protocol', 'symbol': 'NEAR'},
    {'key': 'worldcoin', 'name': 'Worldcoin', 'symbol': 'WLD'},
    {'key': 'kaspa', 'name': 'Kaspa', 'symbol': 'KAS'},
    {'key': 'flare', 'name': 'Flare', 'symbol': 'FLR'},
    {'key': 'immutable', 'name': 'Immutable', 'symbol': 'IMX'},
    {'key': 'pax-gold', 'name': 'PAX Gold', 'symbol': 'PAXG'},
    {'key': 'myx-finance', 'name': 'MYX Finance', 'symbol': 'MYX'},
    {'key': 'ether-fi', 'name': 'ether.fi', 'symbol': 'ETHFI'},
    {'key': 'raydium', 'name': 'Raydium', 'symbol': 'RAY'},
    {'key': 'ab', 'name': 'AB', 'symbol': 'AB'},
    {'key': 'layerzero', 'name': 'LayerZero', 'symbol': 'ZRO'},
    {'key': 'wormhole', 'name': 'Wormhole', 'symbol': 'W'},
    {'key': 'zebec-network', 'name': 'Zebec Network', 'symbol': 'ZBCN'},
    {'key': 'apecoin', 'name': 'ApeCoin', 'symbol': 'APE'},
    {'key': 'core', 'name': 'Core', 'symbol': 'CORE'},
    {'key': 'zora', 'name': 'ZORA', 'symbol': 'ZORA'},
    {'key': 'aioz-network', 'name': 'AIOZ Network', 'symbol': 'AIOZ'},
    {'key': 'movement', 'name': 'Movement', 'symbol': 'MOVE'},
    {'key': 'mog-coin', 'name': 'Mog Coin', 'symbol': 'MOG'},
    {'key': 'kusama', 'name': 'Kusama', 'symbol': 'KSM'},
    {'key': 'theta-fuel', 'name': 'Theta Fuel', 'symbol': 'TFUEL'},
    {'key': 'chainopera-ai', 'name': 'ChainOpera AI', 'symbol': 'COAI'},
    {'key': 'beldex', 'name': 'Beldex', 'symbol': 'BDX'},
    {'key': 'gho', 'name': 'GHO', 'symbol': 'GHO'},
    {'key': 'nexusmind', 'name': 'Nexusmind', 'symbol': 'NMD'},
    {'key': '0x-protocol', 'name': '0x Protocol', 'symbol': 'ZRX'},
    {'key': 'mina', 'name': 'Mina', 'symbol': 'MINA'},
    {'key': 'grass', 'name': 'Grass', 'symbol': 'GRASS'},
    {'key': 'blur', 'name': 'Blur', 'symbol': 'BLUR'},
    {'key': 'space-id', 'name': 'SPACE ID', 'symbol': 'ID'},
    {'key': 'centrifuge', 'name': 'Centrifuge', 'symbol': 'CFG'},
    {'key': 'holo', 'name': 'Holo', 'symbol': 'HOT'},
    {'key': 'cow-protocol', 'name': 'CoW Protocol', 'symbol': 'COW'},
    {'key': 'redstone', 'name': 'RedStone', 'symbol': 'RED'},
    {'key': 'stargate-finance', 'name': 'Stargate Finance', 'symbol': 'STG'},
    {'key': 'chia', 'name': 'Chia', 'symbol': 'XCH'},
    {'key': 'xyo', 'name': 'XYO', 'symbol': 'XYO'},
    {'key': 'hashkey-platform-token', 'name': 'HashKey Platform Token', 'symbol': 'HSK'},
    {'key': 'vana', 'name': 'Vana', 'symbol': 'VANA'},
    {'key': 'neiro', 'name': 'Neiro', 'symbol': 'NEIRO'},
    {'key': 'lista-dao', 'name': 'Lista DAO', 'symbol': 'LISTA'},
    {'key': 'kub-coin', 'name': 'KUB Coin', 'symbol': 'KUB'},
    {'key': 'metamask-usd', 'name': 'MetaMask USD', 'symbol': 'MUSD'},
    {'key': 'venice-token', 'name': 'Venice Token', 'symbol': 'VVV'},
    {'key': 'iexec-rlc', 'name': 'iExec RLC', 'symbol': 'RLC'},
    {'key': 'multibank-group', 'name': 'MultiBank Group', 'symbol': 'MBG'},
    {'key': 'iost', 'name': 'IOST', 'symbol': 'IOST'},
    {'key': 'spark', 'name': 'Spark', 'symbol': 'SPK'},
    {'key': 'unibase', 'name': 'Unibase', 'symbol': 'UB'},
    {'key': 'wiki-cat', 'name': 'Wiki Cat', 'symbol': 'WKC'},
    {'key': 'bless', 'name': 'Bless', 'symbol': 'BLESS'},
    {'key': 'jelly-my-jelly', 'name': 'Jelly-My-Jelly', 'symbol': 'JELLYJELLY'},
    {'key': 'audius', 'name': 'Audius', 'symbol': 'AUDIO'},
    {'key': 'iq', 'name': 'IQ', 'symbol': 'IQ'},
    {'key': 'keep-network', 'name': 'Keep Network', 'symbol': 'KEEP'},
    {'key': 'tradoor', 'name': 'Tradoor', 'symbol': 'TRADOOR'},
    {'key': 'renzo', 'name': 'Renzo', 'symbol': 'REZ'},
    {'key': 'celer-network', 'name': 'Celer Network', 'symbol': 'CELR'},
  ],
  'CORE_5': [
    {'key': 'bnb', 'name': 'BNB', 'symbol': 'BNB'},
    {'key': 'ethena-usde', 'name': 'Ethena USDe', 'symbol': 'USDE'},
    {'key': 'unus-sed-leo', 'name': 'UNUS SED LEO', 'symbol': 'LEO'},
    {'key': 'uniswap', 'name': 'Uniswap', 'symbol': 'UNI'},
    {'key': 'aptos', 'name': 'Aptos', 'symbol': 'APT'},
    {'key': 'world-liberty-financial-usd', 'name': 'World Liberty Financial USD', 'symbol': 'USD1'},
    {'key': 'pump-fun', 'name': 'Pump.fun', 'symbol': 'PUMP'},
    {'key': 'render', 'name': 'Render', 'symbol': 'RENDER'},
    {'key': 'spx6900', 'name': 'SPX6900', 'symbol': 'SPX'},
    {'key': 'injective', 'name': 'Injective', 'symbol': 'INJ'},
    {'key': 'tether-gold', 'name': 'Tether Gold', 'symbol': 'XAUT'},
    {'key': 'nexo', 'name': 'Nexo', 'symbol': 'NEXO'},
    {'key': 'tezos', 'name': 'Tezos', 'symbol': 'XTZ'},
    {'key': 'starknet', 'name': 'Starknet', 'symbol': 'STRK'},
    {'key': 'jito', 'name': 'Jito', 'symbol': 'JTO'},
    {'key': 'trueusd', 'name': 'TrueUSD', 'symbol': 'TUSD'},
    {'key': 'dydx', 'name': 'dYdX', 'symbol': 'DYDX'},
    {'key': 'toshi', 'name': 'Toshi', 'symbol': 'TOSHI'},
    {'key': 'multiversx', 'name': 'MultiversX', 'symbol': 'EGLD'},
    {'key': 'reserve-rights', 'name': 'Reserve Rights', 'symbol': 'RSR'},
    {'key': 'ronin', 'name': 'Ronin', 'symbol': 'RON'},
    {'key': 'moca-network', 'name': 'Moca Network', 'symbol': 'MOCA'},
    {'key': 'akash-network', 'name': 'Akash Network', 'symbol': 'AKT'},
    {'key': 'buildon', 'name': 'BUILDon', 'symbol': 'B'},
    {'key': 'popcat-sol', 'name': 'Popcat (SOL)', 'symbol': 'POPCAT'},
    {'key': 'fasttoken', 'name': 'Fasttoken', 'symbol': 'FTN'},
    {'key': 'swissborg', 'name': 'SwissBorg', 'symbol': 'BORG'},
    {'key': 'aster-usdf', 'name': 'Aster USDF', 'symbol': 'USDF'},
    {'key': 'qubic', 'name': 'Qubic', 'symbol': 'QUBIC'},
    {'key': 'zilliqa', 'name': 'Zilliqa', 'symbol': 'ZIL'},
    {'key': 'nervos-network', 'name': 'Nervos Network', 'symbol': 'CKB'},
    {'key': 'frax-prev-fxs', 'name': 'Frax (prev. FXS)', 'symbol': 'FRAX'},
    {'key': 'zetachain', 'name': 'ZetaChain', 'symbol': 'ZETA'},
    {'key': 'dora', 'name': 'DORA', 'symbol': 'DORA'},
    {'key': 'peaq', 'name': 'peaq', 'symbol': 'PEAQ'},
    {'key': 'moo-deng-moodengsol-com', 'name': 'Moo Deng (moodengsol.com)', 'symbol': 'MOODENG'},
    {'key': 'gmx', 'name': 'GMX', 'symbol': 'GMX'},
    {'key': 'bouncebit', 'name': 'BounceBit', 'symbol': 'BB'},
    {'key': 'ausd', 'name': 'AUSD', 'symbol': 'AUSD'},
    {'key': 'mask-network', 'name': 'Mask Network', 'symbol': 'MASK'},
    {'key': 'slt', 'name': 'SLT', 'symbol': 'SLT'},
    {'key': 'staika', 'name': 'Staika', 'symbol': 'STIK'},
    {'key': 'enjin-coin', 'name': 'Enjin Coin', 'symbol': 'ENJ'},
    {'key': 'vicicoin', 'name': 'ViciCoin', 'symbol': 'VCNT'},
    {'key': 'nano', 'name': 'Nano', 'symbol': 'XNO'},
    {'key': 'victoria-vr', 'name': 'Victoria VR', 'symbol': 'VR'},
    {'key': 'gohome', 'name': 'GOHOME', 'symbol': 'GOHOME'},
    {'key': 'storj', 'name': 'Storj', 'symbol': 'STORJ'},
    {'key': 'destra-network', 'name': 'Destra Network', 'symbol': 'DSYNC'},
    {'key': 'ika', 'name': 'Ika', 'symbol': 'IKA'},
    {'key': 'lisusd', 'name': 'lisUSD', 'symbol': 'LISUSD'},
    {'key': 'open-campus', 'name': 'Open Campus', 'symbol': 'EDU'},
    {'key': 'stronghold-shx', 'name': 'Stronghold SHx', 'symbol': 'SHX'},
    {'key': 'pixels', 'name': 'Pixels', 'symbol': 'PIXEL'},
    {'key': 'bancor', 'name': 'Bancor', 'symbol': 'BNT'},
    {'key': 'balancer', 'name': 'Balancer', 'symbol': 'BAL'},
    {'key': 'spell-token', 'name': 'Spell Token', 'symbol': 'SPELL'},
    {'key': 'cookie-dao', 'name': 'Cookie DAO', 'symbol': 'COOKIE'},
    {'key': 'banana-gun', 'name': 'Banana Gun', 'symbol': 'BANANA'},
    {'key': 'camp-network', 'name': 'Camp Network', 'symbol': 'CAMP'},
    {'key': 'uchain', 'name': 'Uchain', 'symbol': 'UCN'},
    {'key': 'collector-crypt', 'name': 'Collector Crypt', 'symbol': 'CARDS'},
  ],
  'CORE_6': [
    {'key': 'xrp', 'name': 'XRP', 'symbol': 'XRP'},
    {'key': 'hyperliquid', 'name': 'Hyperliquid', 'symbol': 'HYPE'},
    {'key': 'mantle', 'name': 'Mantle', 'symbol': 'MNT'},
    {'key': 'world-liberty-financial', 'name': 'World Liberty Financial', 'symbol': 'WLFI'},
    {'key': 'zcash', 'name': 'Zcash', 'symbol': 'ZEC'},
    {'key': 'paypal-usd', 'name': 'PayPal USD', 'symbol': 'PYUSD'},
    {'key': 'algorand', 'name': 'Algorand', 'symbol': 'ALGO'},
    {'key': 'filecoin', 'name': 'Filecoin', 'symbol': 'FIL'},
    {'key': 'gatetoken', 'name': 'GateToken', 'symbol': 'GT'},
    {'key': 'artificial-superintelligence-alliance', 'name': 'Artificial Superintelligence Alliance', 'symbol': 'FET'},
    {'key': 'aerodrome-finance', 'name': 'Aerodrome Finance', 'symbol': 'AERO'},
    {'key': 'ripple-usd', 'name': 'Ripple USD', 'symbol': 'RLUSD'},
    {'key': 'gala', 'name': 'Gala', 'symbol': 'GALA'},
    {'key': 'aethir', 'name': 'Aethir', 'symbol': 'ATH'},
    {'key': 'bittorrent-new', 'name': 'BitTorrent [New]', 'symbol': 'BTT'},
    {'key': 'bitcoin-sv', 'name': 'Bitcoin SV', 'symbol': 'BSV'},
    {'key': 'zksync', 'name': 'ZKsync', 'symbol': 'ZK'},
    {'key': 'chiliz', 'name': 'Chiliz', 'symbol': 'CHZ'},
    {'key': 'useless-coin', 'name': 'Useless Coin', 'symbol': 'USELESS'},
    {'key': 'ecash', 'name': 'eCash', 'symbol': 'XEC'},
    {'key': 'just', 'name': 'JUST', 'symbol': 'JST'},
    {'key': 'terra-classic', 'name': 'Terra Classic', 'symbol': 'LUNC'},
    {'key': 'creditcoin', 'name': 'Creditcoin', 'symbol': 'CTC'},
    {'key': 'origintrail', 'name': 'OriginTrail', 'symbol': 'TRAC'},
    {'key': 'golem', 'name': 'Golem', 'symbol': 'GLM'},
    {'key': 'global-dollar', 'name': 'Global Dollar', 'symbol': 'USDG'},
    {'key': 'usdai', 'name': 'USDai', 'symbol': 'USDAI'},
    {'key': 'kinesis-gold', 'name': 'Kinesis Gold', 'symbol': 'KAU'},
    {'key': 'celo', 'name': 'Celo', 'symbol': 'CELO'},
    {'key': 'ailey', 'name': 'Ailey', 'symbol': 'ALE'},
    {'key': 'euler', 'name': 'Euler', 'symbol': 'EUL'},
    {'key': 'aleo', 'name': 'Aleo', 'symbol': 'ALEO'},
    {'key': 'alchemy-pay', 'name': 'Alchemy Pay', 'symbol': 'ACH'},
    {'key': '4', 'name': '4', 'symbol': '4'},
    {'key': 'succinct', 'name': 'Succinct', 'symbol': 'PROVE'},
    {'key': 'humanity-protocol', 'name': 'Humanity Protocol', 'symbol': 'H'},
    {'key': 'fellaz', 'name': 'Fellaz', 'symbol': 'FLZ'},
    {'key': 'deagentai', 'name': 'DeAgentAI', 'symbol': 'AIA'},
    {'key': 'yzy-money', 'name': 'YZY MONEY', 'symbol': 'YZY'},
    {'key': 'yala', 'name': 'Yala', 'symbol': 'YU'},
    {'key': 'casper', 'name': 'Casper', 'symbol': 'CSPR'},
    {'key': 'gmt', 'name': 'GMT', 'symbol': 'GMT'},
    {'key': 'elixir-deusd', 'name': 'Elixir deUSD', 'symbol': 'DEUSD'},
    {'key': 'ssv-network', 'name': 'ssv.network', 'symbol': 'SSV'},
    {'key': 'stbl', 'name': 'STBL', 'symbol': 'STBL'},
    {'key': 'nexpace', 'name': 'NEXPACE', 'symbol': 'NXPC'},
    {'key': 'space-and-time', 'name': 'Space and Time', 'symbol': 'SXT'},
    {'key': 'orderly', 'name': 'Orderly', 'symbol': 'ORDER'},
    {'key': 'blast', 'name': 'Blast', 'symbol': 'BLAST'},
    {'key': 'biconomy', 'name': 'Biconomy', 'symbol': 'BICO'},
    {'key': 'bora', 'name': 'BORA', 'symbol': 'BORA'},
    {'key': 'hemi', 'name': 'Hemi', 'symbol': 'HEMI'},
    {'key': 'xai', 'name': 'Xai', 'symbol': 'XAI'},
    {'key': 'powerledger', 'name': 'Powerledger', 'symbol': 'POWR'},
    {'key': 'bonfida', 'name': 'Bonfida', 'symbol': 'FIDA'},
    {'key': 'ecomi', 'name': 'ECOMI', 'symbol': 'OMI'},
    {'key': 'tutorial', 'name': 'Tutorial', 'symbol': 'TUT'},
    {'key': 'og-fan-token', 'name': 'OG Fan Token', 'symbol': 'OG'},
    {'key': 'mnee', 'name': 'MNEE', 'symbol': 'MNEE'},
    {'key': 'chaingpt', 'name': 'ChainGPT', 'symbol': 'CGPT'},
    {'key': 'ape-and-pepe', 'name': 'Ape and Pepe', 'symbol': 'APEPE'},
    {'key': 'dymension', 'name': 'Dymension', 'symbol': 'DYM'},
  ],
  'CORE_7': [
    {'key': 'solana', 'name': 'Solana', 'symbol': 'SOL'},
    {'key': 'sui', 'name': 'Sui', 'symbol': 'SUI'},
    {'key': 'shiba-inu', 'name': 'Shiba Inu', 'symbol': 'SHIB'},
    {'key': 'okb', 'name': 'OKB', 'symbol': 'OKB'},
    {'key': 'bittensor', 'name': 'Bittensor', 'symbol': 'TAO'},
    {'key': 'polygon-prev-matic', 'name': 'Polygon (prev. MATIC)', 'symbol': 'POL'},
    {'key': 'cosmos', 'name': 'Cosmos', 'symbol': 'ATOM'},
    {'key': 'sky', 'name': 'Sky', 'symbol': 'SKY'},
    {'key': 'doublezero', 'name': 'DoubleZero', 'symbol': '2Z'},
    {'key': 'celestia', 'name': 'Celestia', 'symbol': 'TIA'},
    {'key': 'dexe', 'name': 'DeXe', 'symbol': 'DEXE'},
    {'key': 'sonic', 'name': 'Sonic', 'symbol': 'S'},
    {'key': 'theta-network', 'name': 'Theta Network', 'symbol': 'THETA'},
    {'key': 'trust-wallet-token', 'name': 'Trust Wallet Token', 'symbol': 'TWT'},
    {'key': 'flow', 'name': 'Flow', 'symbol': 'FLOW'},
    {'key': 'sun-new', 'name': 'Sun [New]', 'symbol': 'SUN'},
    {'key': 'dash', 'name': 'Dash', 'symbol': 'DASH'},
    {'key': 'thorchain', 'name': 'THORChain', 'symbol': 'RUNE'},
    {'key': 'arweave', 'name': 'Arweave', 'symbol': 'AR'},
    {'key': 'superverse', 'name': 'SuperVerse', 'symbol': 'SUPER'},
    {'key': 'kaito', 'name': 'KAITO', 'symbol': 'KAITO'},
    {'key': 'drift', 'name': 'Drift', 'symbol': 'DRIFT'},
    {'key': 'eurc', 'name': 'EURC', 'symbol': 'EURC'},
    {'key': 'mx-token', 'name': 'MX Token', 'symbol': 'MX'},
    {'key': 'baby-doge-coin', 'name': 'Baby Doge Coin', 'symbol': 'BABYDOGE'},
    {'key': 'saros', 'name': 'Saros', 'symbol': 'SAROS'},
    {'key': 'fluid', 'name': 'Fluid', 'symbol': 'FLUID'},
    {'key': 'legacy-frax-dollar', 'name': 'Legacy Frax Dollar', 'symbol': 'FRAX'},
    {'key': 'velo', 'name': 'Velo', 'symbol': 'VELO'},
    {'key': 'keeta', 'name': 'Keeta', 'symbol': 'KTA'},
    {'key': 'sushiswap', 'name': 'SushiSwap', 'symbol': 'SUSHI'},
    {'key': 'prom', 'name': 'Prom', 'symbol': 'PROM'},
    {'key': 'ravencoin', 'name': 'Ravencoin', 'symbol': 'RVN'},
    {'key': 'lombard', 'name': 'Lombard', 'symbol': 'BARD'},
    {'key': 'threshold', 'name': 'Threshold', 'symbol': 'T'},
    {'key': 'ethereumpow', 'name': 'EthereumPoW', 'symbol': 'ETHW'},
    {'key': 'skale', 'name': 'SKALE', 'symbol': 'SKL'},
    {'key': 'ankr', 'name': 'Ankr', 'symbol': 'ANKR'},
    {'key': 'woo', 'name': 'WOO', 'symbol': 'WOO'},
    {'key': 'lcx', 'name': 'LCX', 'symbol': 'LCX'},
    {'key': 'orca', 'name': 'Orca', 'symbol': 'ORCA'},
    {'key': 'kadena', 'name': 'Kadena', 'symbol': 'KDA'},
    {'key': 'polymesh', 'name': 'Polymesh', 'symbol': 'POLYX'},
    {'key': 'reallink', 'name': 'RealLink', 'symbol': 'REAL'},
    {'key': 'uma', 'name': 'UMA', 'symbol': 'UMA'},
    {'key': 'solar', 'name': 'Solar', 'symbol': 'SXP'},
    {'key': 'wilder-world', 'name': 'Wilder World', 'symbol': 'WILD'},
    {'key': 'terra', 'name': 'Terra', 'symbol': 'LUNA'},
    {'key': 'portal-to-bitcoin', 'name': 'Portal To Bitcoin', 'symbol': 'PTB'},
    {'key': 'aixbt', 'name': 'aixbt', 'symbol': 'AIXBT'},
    {'key': 'metis', 'name': 'Metis', 'symbol': 'METIS'},
    {'key': 'constitutiondao', 'name': 'ConstitutionDAO', 'symbol': 'PEOPLE'},
    {'key': 'goatseus-maximus', 'name': 'Goatseus Maximus', 'symbol': 'GOAT'},
    {'key': 'defi-app', 'name': 'Defi App', 'symbol': 'HOME'},
    {'key': 'stratis-new', 'name': 'Stratis [New]', 'symbol': 'STRAX'},
    {'key': 'animecoin', 'name': 'Animecoin', 'symbol': 'ANIME'},
    {'key': 'okzoo', 'name': 'OKZOO', 'symbol': 'AIOT'},
    {'key': 'flux', 'name': 'Flux', 'symbol': 'FLUX'},
    {'key': 'across-protocol', 'name': 'Across Protocol', 'symbol': 'ACX'},
    {'key': 'sonic-svm', 'name': 'Sonic SVM', 'symbol': 'SONIC'},
    {'key': 'taiko', 'name': 'Taiko', 'symbol': 'TAIKO'},
    {'key': 'zentry', 'name': 'Zentry', 'symbol': 'ZENT'},
  ],
  'CORE_8': [
    {'key': 'usdc', 'name': 'USDC', 'symbol': 'USDC'},
    {'key': 'stellar', 'name': 'Stellar', 'symbol': 'XLM'},
    {'key': 'toncoin', 'name': 'Toncoin', 'symbol': 'TON'},
    {'key': 'aave', 'name': 'Aave', 'symbol': 'AAVE'},
    {'key': 'ethereum-classic', 'name': 'Ethereum Classic', 'symbol': 'ETC'},
    {'key': 'internet-computer', 'name': 'Internet Computer', 'symbol': 'ICP'},
    {'key': 'pudgy-penguins', 'name': 'Pudgy Penguins', 'symbol': 'PENGU'},
    {'key': 'bonk', 'name': 'Bonk', 'symbol': 'BONK'},
    {'key': 'xdc-network', 'name': 'XDC Network', 'symbol': 'XDC'},
    {'key': 'first-digital-usd', 'name': 'First Digital USD', 'symbol': 'FDUSD'},
    {'key': 'pyth-network', 'name': 'Pyth Network', 'symbol': 'PYTH'},
    {'key': 'ethereum-name-service', 'name': 'Ethereum Name Service', 'symbol': 'ENS'},
    {'key': 'dogwifhat', 'name': 'dogwifhat', 'symbol': 'WIF'},
    {'key': 'fartcoin', 'name': 'Fartcoin', 'symbol': 'FARTCOIN'},
    {'key': 'morpho', 'name': 'Morpho', 'symbol': 'MORPHO'},
    {'key': 'helium', 'name': 'Helium', 'symbol': 'HNT'},
    {'key': 'apenft', 'name': 'APENFT', 'symbol': 'NFT'},
    {'key': 'compound', 'name': 'Compound', 'symbol': 'COMP'},
    {'key': 'onyxcoin', 'name': 'Onyxcoin', 'symbol': 'XCN'},
    {'key': '1inch', 'name': '1inch', 'symbol': '1INCH'},
    {'key': 'convex-finance', 'name': 'Convex Finance', 'symbol': 'CVX'},
    {'key': 'snek', 'name': 'Snek', 'symbol': 'SNEK'},
    {'key': 'basic-attention-token', 'name': 'Basic Attention Token', 'symbol': 'BAT'},
    {'key': 'turbo', 'name': 'Turbo', 'symbol': 'TURBO'},
    {'key': 'kamino-finance', 'name': 'Kamino Finance', 'symbol': 'KMNO'},
    {'key': 'zeebu', 'name': 'Zeebu', 'symbol': 'ZBU'},
    {'key': 'loaded-lions', 'name': 'Loaded Lions', 'symbol': 'LION'},
    {'key': 'soon', 'name': 'SOON', 'symbol': 'SOON'},
    {'key': 'concordium', 'name': 'Concordium', 'symbol': 'CCD'},
    {'key': 'sosovalue', 'name': 'SoSoValue', 'symbol': 'SOSO'},
    {'key': 'gas', 'name': 'Gas', 'symbol': 'GAS'},
    {'key': 'awe', 'name': 'AWE', 'symbol': 'AWE'},
    {'key': 'yearn-finance', 'name': 'yearn.finance', 'symbol': 'YFI'},
    {'key': 'ordi', 'name': 'ORDI', 'symbol': 'ORDI'},
    {'key': 'notcoin', 'name': 'Notcoin', 'symbol': 'NOT'},
    {'key': 'siacoin', 'name': 'Siacoin', 'symbol': 'SC'},
    {'key': 'rollbit-coin', 'name': 'Rollbit Coin', 'symbol': 'RLB'},
    {'key': 'harmony', 'name': 'Harmony', 'symbol': 'ONE'},
    {'key': 'venom', 'name': 'Venom', 'symbol': 'VENOM'},
    {'key': 'shuffle', 'name': 'Shuffle', 'symbol': 'SHFL'},
    {'key': 'bitmart-token', 'name': 'BitMart Token', 'symbol': 'BMX'},
    {'key': 'launch-coin-on-believe', 'name': 'Launch Coin on Believe', 'symbol': 'LAUNCHCOIN'},
    {'key': 'waves', 'name': 'Waves', 'symbol': 'WAVES'},
    {'key': 'book-of-meme', 'name': 'BOOK OF MEME', 'symbol': 'BOME'},
    {'key': 'rocket-pool', 'name': 'Rocket Pool', 'symbol': 'RPL'},
    {'key': 'clearpool', 'name': 'Clearpool', 'symbol': 'CPOOL'},
    {'key': 'gravity-by-galxe', 'name': 'Gravity (by Galxe)', 'symbol': 'G'},
    {'key': 'nillion', 'name': 'Nillion', 'symbol': 'NIL'},
    {'key': 'harrypotterobamasonic10inu-erc-20', 'name': 'HarryPotterObamaSonic10Inu (ERC-20)', 'symbol': 'BITCOIN'},
    {'key': 'hive', 'name': 'Hive', 'symbol': 'HIVE'},
    {'key': 'osaka-protocol', 'name': 'Osaka Protocol', 'symbol': 'OSAK'},
    {'key': 'sign', 'name': 'Sign', 'symbol': 'SIGN'},
    {'key': 'civic', 'name': 'Civic', 'symbol': 'CVC'},
    {'key': 'phala-network', 'name': 'Phala Network', 'symbol': 'PHA'},
    {'key': 'wax', 'name': 'WAX', 'symbol': 'WAXP'},
    {'key': 'bertram-the-pomeranian', 'name': 'Bertram The Pomeranian', 'symbol': 'BERT'},
    {'key': 'chromia', 'name': 'Chromia', 'symbol': 'CHR'},
    {'key': 'chintai', 'name': 'Chintai', 'symbol': 'CHEX'},
    {'key': 'propy', 'name': 'Propy', 'symbol': 'PRO'},
    {'key': 'holoworld-ai', 'name': 'Holoworld AI', 'symbol': 'HOLO'},
    {'key': 'mil-k', 'name': 'MiL.k', 'symbol': 'MLK'},
    {'key': 'delysium', 'name': 'Delysium', 'symbol': 'AGI'},
  ],
}

# --- merge core + meme buckets ---
from symbol_buckets_core import BUCKETS as CORE_BUCKETS
from symbol_buckets_memes import BUCKETS as MEME_BUCKETS

BUCKETS = {}
BUCKETS.update(CORE_BUCKETS)
BUCKETS.update(MEME_BUCKETS)

# Suggested schedule (UTC)
# CORE_1 :00, CORE_2 :07, CORE_3 :14, CORE_4 :21, CORE_5 :28, CORE_6 :35, CORE_7 :42, CORE_8 :49
# MEME_1 :02, MEME_2 :09, MEME_3 :16, MEME_4 :23, MEME_5 :30, MEME_6 :37, MEME_7 :44, MEME_8 :51
